apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesJson6902:
- target:
    kind: DeploymentConfig
    version: v1
    group: apps.openshift.io
    name: kamhub-db # {"$openapi":"APPLICATION_DB_NAME"}
  path: jupyterhub-db.patch
