apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- third-party
- overlays/opendatahub
commonLabels:
  application-crd-id: kubeflow-pipelines
namespace: opendatahub-kfp-tekton
