apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-workflows//manifests/cluster-install/?ref=stable
patches:
- path: argo-server-deployment.yaml
  target:
    kind: Deployment
    name: argo-server
- path: workflow-controller-configmap.yaml
  target:
    kind: ConfigMap
    name: workflow-controller-configmap
namespace: argo
