apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ml-pipeline-ui
  name: ml-pipeline
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: ml-pipeline-ui
    weight: 100
