apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config-map.yaml
- ../../../base
patchesJson6902:
- target:
    kind: DeploymentConfig
    version: v1
    group: apps.openshift.io
    name: jupyterhub # {"$openapi":"APPLICATION_NAME"}
  path: jupyterhub.patch
