apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      profiles:
      - name: globals
        env:
          - name: S3_ENDPOINT_URL
            value: s3.odh.com # {"$openapi":"S3_ENDPOINT_URL"}
