apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds
- https://raw.githubusercontent.com/kubeflow/kfp-tekton/v0.8.0-rc0/manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
- https://raw.githubusercontent.com/kubeflow/kfp-tekton/v0.8.0-rc0/manifests/kustomize/base/installs/generic/mysql-secret.yaml
- github.com/kubeflow/kfp-tekton//manifests/kustomize/base/pipeline/?ref=v0.8.0-rc0
- github.com/kubeflow/kfp-tekton//manifests/kustomize/base/metadata/base/?ref=v0.8.0-rc0
#- github.com/kubeflow/kfp-tekton//manifests/kustomize/base/cache/?ref=v0.8.0-rc0
#- github.com/kubeflow/kfp-tekton//manifests/kustomize/base/cache-deployer/?ref=v0.8.0-rc0
