apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jupyterhub/overrides/overlays/jupyterhub-deployment-patch
- notebook-images/overlays/additional
namespace: redhat-ods-applications # {"$openapi":"NAMESPACE_NAME"}
