apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kamhub # {"$openapi":"APPLICATION_NAME"}
  name: kamhub # {"$openapi":"APPLICATION_NAME"}
spec:
  host: ''
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kamhub # {"$openapi":"APPLICATION_NAME"}
    weight: 100
