apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kamhub # {"$openapi":"APPLICATION_NAME"}
  name: kamhub-nodereader # {"$openapi":"APPLICATION_NODEREADER_NAME"}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:node-reader'
subjects:
- kind: ServiceAccount
  name: kamhub-hub # {"$openapi":"APPLICATION_HUB_NAME"}
