apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-db # {"$openapi":"JUPYTERHUB_STORAGE_NAME"}
  annotations:
    volume.beta.kubernetes.io/storage-class: gcp # {"$openapi":"STORAGE_CLASS"}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
