apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyterhub # {"$openapi":"APPLICATION_NAME"}
  name: jupyterhub-db # {"$openapi":"APPLICATION_DB_NAME"}
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: jupyterhub # {"$openapi":"APPLICATION_NAME"}
    deploymentconfig: jupyterhub-db # {"$openapi":"APPLICATION_DB_NAME"}
