apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub # {"$openapi":"APPLICATION_NAME"}
  name: jupyterhub-cfg # {"$openapi":"APPLICATION_CFG_NAME"}
data:
  jupyterhub_config.py: ""
  jupyterhub_admins: "admin"
  gpu_mode: ""
  singleuser_pvc_size: 2Gi
