apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jupyterhub-configmap.yaml
- jupyterhub-secret.yaml
- jupyterhub-db-pvc.yaml
- jupyterhub-db-dc.yaml
- jupyterhub-db-service.yaml
- jupyterhub-img-imagestream.yaml
- jupyterhub-dc.yaml
- jupyterhub-service.yaml
- jupyterhub-serviceaccount.yaml
- jupyterhub-role.yaml
- jupyterhub-rolebinding.yaml
- jupyterhub-nodereader-rolebinding.yaml
- jupyterhub-route.yaml
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub # {"$openapi":"JUPYTERHUB_NAME"}
